version: 0.2
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run affected:build -- --base=origin/main --parallel --prod
  post_build:
    commands:
      - aws s3 sync dist/apps/app1 s3://shell-app-101 --delete
      - aws s3 sync dist/apps/app2 s3://mfe-app-101 --delete
artifacts:
  files:
    - '**/*'
